project_id = "wturfdjywbpzassyuwun"

[functions.ancine_proxy]
verify_jwt = false

[functions.asset_metadata]
verify_jwt = false

[functions.clube_news]
verify_jwt = false

[functions.finance_import]

[functions.google_sheets_sync]
verify_jwt = false

[functions.rights_sync]
verify_jwt = false