// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';


const REACT_APP_SUPABASE_URL="https://wturfdjywbpzassyuwun.supabase.co"
const REACT_APP_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dXJmZGp5d2JwemFzc3l1d3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODk0MTYsImV4cCI6MjA3NDY2NTQxNn0.cAKbRbNUGcH-gbUSfMXzf6BIDNKsRhuWrenUd2ojguk"
//// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(REACT_APP_SUPABASE_URL, REACT_APP_SUPABASE_ANON_KEY,{
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,

    // src/integrations/supabase/client.ts
import { createClient } from '@supabase/supabase-js';


const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;


export const supabase = createClient(url, anon);
  }
});